name: Lesson 01 - Hello World


on:
  workflow_dispatch:  
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths-ignore:
  #     - '**.md'
  #     - 'docs/**'
  
  # pull_request:
  #   branches:
  #     - main
  
jobs:
  hello-job:
    name: Say Hello
    runs-on: ubuntu-latest
    
    steps:
      - name: Print greeting
        run: echo "Hello, GitHub Actions!"
      
      - name: Print date
        run: date
      
      - name: Print working directory
        run: pwd
      
      - name: List files
        run: |
          echo "Listing files in current directory:"
          ls -la
